---
dev_db:
  image: postgres:latest
  ports:
    - 5432:5432
  volumes_from:
    - dev_storage
  environment:
    POSTGRES_DB: realtime
    POSTGRES_USER: realtime
    POSTGRES_PASSWORD: realtime

dev_redis:
  image: redis:latest
  ports:
    - "6379:6379"
  volumes_from:
    - dev_storage
  command: redis-server --appendonly yes

dev_nginx:
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - dev_webapp:app
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/dev-realtime-tool.conf:/etc/nginx/conf.d/dev-realtime-tool.conf
  volumes_from:
    - dev_webapp

dev_webapp:
  build: ./app
  working_dir: "/app"
  command: "ls"
  volumes:
    - .:/app
  expose:
    - "8000"
  links:
    - dev_db:db
    - dev_redis:redis
  command: bash -c "./app/manage.py migrate && ./app/manage.py runserver 0.0.0.0:8000"

dev_storage:
  image: busybox
  volumes:
      - /var/lib/postgresql/data
      - /data
